### ISSUE TITLE
EverestCORE does not output any voltage on motor terminals

### ISSUE THREAD

**Issue by thebolt** [ingeniamc/mcblib#4]
I have got basic communication (using mcblib + helper functions) between my MCU and the EverstCORE module. I can read out the absolute encoder feedback (BiSS connected) properly so I assume the setting parameters code is ok.

When I try to follow the guide at https://doc.ingeniamc.com/summit/manuals/summit-reference-manual/tricks-and-tips/motor-phasing-guide-commutation-alignment to get an initial movement and verify direction, I do not get any movement of the motor or any voltage on the motor terminals (as measured with an oscilloscope)

I have attached a log that shows all register writes that is done, as well as the status register (and error register) read-backs during the operations.
[ecore1.log](https://github.com/ingeniamc/mcblib/files/4298009/ecore1.log)

**Comment by ghost** [comment]
Hi,

The sequence is correct. It seems that the drive is reset or something like this because the status word comes back to its initial state 0x250. The expected status word value after sending the 15 command into control word is something like 0x4237. There is only 2 ways to reach the initial state (0x250):

1. After power on
2. Control word command = 0

Could you try to remove the motor phases during this sequence? Maybe there is a very short peak current that is dropping down the power supply and resetting the board.

**Comment by thebolt** [comment]
I did run the sequence (again this morning) without any motor phases, same behavior.

I also added a oscilloscope probe on reset line and on the 48V supply (which by the way has a latching overcurrent limit that does not trigger). Neither reset line nor 48V line has any glitches, at least not that can be picked up with a 100MHz scope.

Any other ideas?

**Comment by ghost** [comment]
Hi,

I see the mistake, is in this line:

Set (u16) 0x0010 = 0x0015 (21)

You should write a 0x000F (15) instead. Tell me if this fixes the issue.

**Comment by thebolt** [comment]
Definitely my mistake, but so easy to make..   Now open-loop rotation of the motor works, and I also got feedback encoder align to work. Later today I will test current mode control (which is what we will use).

Thank you!
